---
baseURL: "/"
languageCode: "en-us"
title: "Fluxnova documentation"
theme: "fluxnova"

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.fluxnova.finos.org"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "0.9"
    versions:
      - "latest"
      - "0.9"
      - "develop"
  
  github:
    repositoryName: "finos/fluxnova-docs-manual"
    branch: "main"    

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
...
